### ISSUE TITLE
Gradle build is not running from  workspace

### ISSUE THREAD

**Issue by nilaytiwari** [IBM/logstash-filter-mongodb-guardium#1]
I followed below steps 

Setting below path in gradle.properties file.

LOGSTASH_CORE_PATH = C:\\logstash-7.13\\logstash-core
GUARDIUM_UNIVERSALCONNECTOR_COMMONS_PATH = C:\\guardium-universalconnector-commons-master\\build\\libs\\guardium-universalconnector-commons-master-1.0.0.jar

also executed build as mentioned in document for logstash-7.13 and universalconnector, all run successfully . 

But when I executed  gradlew assemble on logstash-filter-mongodb-guardium  then I am facing below error 

`* What went wrong:
A problem occurred evaluating script.
> Could not find method register() for arguments [downloadJRuby, class de.undercouch.gradle.tasks.dow
nload.Download, rubyUtils_7c4rvbvd5su7b76bpxzx2zqhk$_run_closure2@44b50385] on task set of type org.gradle.api.
internal.tasks.DefaultTaskContainer.`

My local workspace environment on windows and using gradle distribution  gradle-4.8-bin.zip which is same as in master branch

**Comment by Tal-Daniel** [comment]
Hi, @nilaytiwari, did you install JRuby? I think it's mentioned only in [Developing plug-ins](https://www.ibm.com/docs/en/guardium/11.3?topic=connector-developing-plug-ins) section on IBM documentation. 
After verifying this, try to build only the gem, instead of assemble, using `gradlew gem`(win) or `./gradlew.unix gem`.

**Comment by nilaytiwari** [comment]
Its not because of JRuby, Actually this code build on 7.5 log stash and gradle version 4.8 . And I am trying to build it on 7.13 version of log stash. Issue coming because of gradle version.  I fixed just by modifying rubyUtils.gradle file in logstash folder. 

log statsh 7.5 having downloadJRuby  in rubyUtils.gradle file as given below 

`task verifyFile(dependsOn: downloadJRuby, type: Verify) {
    description "Verify the SHA1 of the download JRuby artifact"
    inputs.file(jrubyTarPath)
    outputs.file(jrubyTarPath)
    src new File(jrubyTarPath)
    algorithm 'SHA-1'
    checksum jRubySha1
}`



But in 7.13 is other way 

`tasks.register("downloadJRuby", Download) {
    description "Download JRuby artifact from this specific URL: ${jRubyURL}"
    src jRubyURL
    onlyIfNewer true
    inputs.file(versionsPath)
    outputs.file(jrubyTarPath)
    dest new File("${projectDir}/vendor/_", "jruby-dist-${jRubyVersion}-bin.tar.gz")
}`


As in this project we are using gradle version gradle-4.8 and in log-stash-7.13 is using gradle version gradle-6.5.1-bin.

**Comment by nilaytiwari** [comment]
After fixing that I am facing this issue on windows 


* What went wrong:
Execution failed for task ':gem'.
> (ESRCH) No such process - vendor/jar-dependencies/com/ibm/guardium/mongodb/logstash-filter-mongodb_guardium_filter/1.0.0/logstash-filter-mongodb_guardium_filter-1.0.0.jar

@Tal-Daniel  please help

**Comment by Tal-Daniel** [comment]
Thanks for pointing out that the version of logstash may be the source of the downloadRuby issue. I suggest these directions @nilaytiwari: 

- Try to install exact versions used in this filter, if possible
- Alternatively, refer to logatash java filter example, which this project is based on, as I see it has updated the embedded/wrapped Gradle to 6.5.1. The gradle.build may also have changed. 
See https://github.com/logstash-plugins/logstash-filter-java_filter_example
- scroll carefully through the gradle build console messages, as they may reveal why the jar was not built in vendor/...

**Comment by nilaytiwari** [comment]
@Tal-Daniel  thanks for Guidance
